### ISSUE TITLE
依赖冲突问题 0.34.0 的 mirai-core-qqandroid-jvm 和 1.1.1 的 mirai-japt 不兼容

### ISSUE THREAD

**Issue by majiaxin110** [mamoe/mirai-japt#2]
按照README中的说明，引入0.34.0版本 的 mirai-core-qqandroid-jvm 和 1.1.1版本 的 mirai-japt 将引发依赖冲突问题，编译后将无法运行。主要原因在于 1.1.1版本 的 mirai-japt 实际依赖的还是 0.22.0 的 mirai-core-qqandroid-jvm。而 BotAccount 、BotFactoryJvmKt 等类在 0.34.0 版本迁移到了包 net.mamoe.mirai.qqandroid 而非 0.22.0 的 net.mamoe.mirai。 从而引发 NoClassDefFoundError. 

![image](https://user-images.githubusercontent.com/28682970/78671956-8e2e6980-7912-11ea-87c4-0224cb0499a4.png)
![image](https://user-images.githubusercontent.com/28682970/78672340-1745a080-7913-11ea-9cb4-806ad7a4521b.png)

因此，是否应考虑更新下 mirai-japt？

环境:
jdk 11.0.5 
maven 3.6.3
macOS 10.15.3

**Comment by majiaxin110** [comment]
类似的，所依赖的kotlin包也有一堆冲突问题

**Comment by Him188** [comment]
japt已弃用。console现在内置 japt

**Comment by Him188** [comment]
使用mirai依赖时请使用 Kotlin. 将不会在这方面继续支持 Java。

若要使用 Java，请使用 mirai-console
